-- SQL schema for Supabase (run in Supabase SQL Editor)

-- members
CREATE TABLE IF NOT EXISTS members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_number text UNIQUE,
  name text NOT NULL,
  nik text,
  birth_date date,
  phone text,
  email text,
  address text,
  status text DEFAULT 'active',
  created_at timestamptz DEFAULT now()
);

-- categories
CREATE TABLE IF NOT EXISTS categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE,
  name text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now()
);

-- incomes
CREATE TABLE IF NOT EXISTS incomes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint REFERENCES categories(id),
  reference text,
  amount numeric,
  date date,
  notes text,
  created_at timestamptz DEFAULT now()
);

-- outcomes
CREATE TABLE IF NOT EXISTS outcomes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint REFERENCES categories(id),
  reference text,
  amount numeric,
  date date,
  notes text,
  created_at timestamptz DEFAULT now()
);

-- debts
CREATE TABLE IF NOT EXISTS debts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  debtor_name text,
  reference text,
  amount numeric,
  due_date date,
  status text DEFAULT 'open',
  created_at timestamptz DEFAULT now()
);

-- employees
CREATE TABLE IF NOT EXISTS employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_number text UNIQUE,
  name text NOT NULL,
  nik text,
  position text,
  phone text,
  email text,
  hired_at date,
  status text DEFAULT 'active',
  created_at timestamptz DEFAULT now()
);

-- employee_salaries
CREATE TABLE IF NOT EXISTS employee_salaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint REFERENCES employees(id),
  amount numeric,
  for_month date,
  remarks text,
  status text DEFAULT 'pending',
  paid_at date,
  created_at timestamptz DEFAULT now()
);

-- loans
CREATE TABLE IF NOT EXISTS loans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_number text UNIQUE,
  member_id bigint REFERENCES members(id),
  principal numeric,
  interest_rate numeric,
  term_months int,
  interest_type text DEFAULT 'flat',
  status text DEFAULT 'applied',
  approved_at date,
  disbursed_at date,
  approved_by bigint,
  created_at timestamptz DEFAULT now()
);

-- loan_installments
CREATE TABLE IF NOT EXISTS loan_installments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id bigint REFERENCES loans(id),
  installment_number int,
  due_date date,
  amount_principal numeric,
  amount_interest numeric,
  amount_total numeric,
  paid_amount numeric DEFAULT 0,
  paid_at date,
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

-- users/profiles (Supabase usually has auth.users; we create profiles table)
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  role text,
  created_at timestamptz DEFAULT now()
);
